function assertBoard(u)
%ASSERTBOARD  Is this the board this repository is about, and will MATLAB talk
%to it? Raise something actionable if not.

    a = fishball.context(u);

    % --- is it the right hardware ---------------------------------------
    model = getfield_(a, 'hw_model', '');
    if isempty(model)
        warning('fishball:board:noModel', ...
                'The board at %s reports no hw_model. Continuing anyway.', u);
    else
        % Match LOOSELY. Two spellings are in service: the device tree says
        % "(Z7020/AD9361)" with a slash and fishball-identity's fallback says
        % "(Z7020-AD9361)" with a dash, so an exact match would reject half the
        % fleet. Test the separator-free parts instead.
        ok = contains(model, 'FISH Ball PlutoSDR') && ...
             contains(model, 'Z7020') && contains(model, 'AD9361');
        if ~ok
            warning('fishball:board:unexpectedModel', ...
                ['hw_model is "%s".\nThis package is written for the ' ...
                 'Fishball7020 / PlutoSky R1 (Z7020 + AD9361). A Z7010 has ' ...
                 'half the fabric;\nan AD9363 is specified to 325 MHz-3.8 GHz ' ...
                 'and 20 MHz of bandwidth rather than 70 MHz-6 GHz and 56.\n' ...
                 'Carrying on, but the measured figures in docs/ will not ' ...
                 'apply.'], model);
        end
    end

    % --- will MATLAB's support package survive the firmware string -------
    fw = getfield_(a, 'fw_version', '');
    if ~isempty(fw) && fishball.internal.breaksMatlab(fw)
        error('fishball:board:firmwareStringBreaksMatlab', ...
          ['This board reports fw_version=%s, and MATLAB''s ADALM-Pluto\n' ...
           'support package cannot connect to a board whose fw_version ' ...
           'looks like a git describe.\n\n' ...
           'It is a bug in the support package, not a fault on your board. ' ...
           'It expects v0.39, and\non anything else it tries to raise ' ...
           'plutoradio:sysobj:FirmwareIncompatible - a message its\n' ...
           'own catalogue marks context="warning" and whose text says "You ' ...
           'can continue using\nversion {1}". It then supplies the wrong ' ...
           'TYPE for one of that message''s five parameters,\nso building ' ...
           'the warning THROWS and the throw aborts the connection.\n\n' ...
           'FIX IT ON THE BOARD. fw_version should carry the release and ' ...
           'fw_build the describe:\n' ...
           '    fw_version=v2.0\n' ...
           '    fw_build=%s\n' ...
           'firmware-modern/debian/overlay/usr/local/sbin/fishball-identity ' ...
           'does this. If your board\npredates that, re-run it, or edit ' ...
           '/etc/libiio.ini and "systemctl restart iiod".\n\n' ...
           'DO NOT let MATLAB''s Hardware Setup App "update the firmware". ' ...
           'It would write a\nZynq-7010 ADALM-Pluto image onto this ' ...
           'Zynq-7020 board. See docs/matlab.md.'], fw, fw);
    end
end

function v = getfield_(s, f, dflt)
    if isfield(s, f), v = s.(f); else, v = dflt; end
end
