function e = explain(e, u)
%EXPLAIN  Turn the two failures people actually hit into readable ones.
    msg = e.message;

    if contains(msg, 'FirmwareIncompatible')
        e = MException('fishball:connect:firmwareStringBreaksMatlab', ...
            ['MATLAB could not connect because it cannot format its own ' ...
             'firmware warning.\nRun fishball.doctor for the explanation ' ...
             'and the one-line fix, or see docs/matlab.md.']);
        return
    end

    if contains(msg, 'already owned')
        e = MException('fishball:connect:alreadyOwned', ...
            ['The radio at %s is already held by another System object in ' ...
             'this MATLAB session.\n\n' ...
             'A FAILED setup leaves it held, so this is usually the ghost ' ...
             'of an earlier error rather than\na second radio. Clear it ' ...
             'with:\n' ...
             '    clear all          %% or release() the object you still have\n\n' ...
             'If it persists, a killed client can leave a session holding ' ...
             'the DMA on the BOARD;\n"killall iiod" over ssh clears that ' ...
             'one and no host-side action will.'], u);
        return
    end
end
